# Default values for opensergo-control-plane.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: opensergo-registry.cn-hangzhou.cr.aliyuncs.com/opensergo/opensergo-control-plane
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
# Overrides selectorLabels
nameOverride: ""
# Overrides namae of metadata
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

namespace:
  name: opensergo-system

deployment:
  opensergoControlPlane:
    port: 10246

service:
  # type: Valid options are ClusterIP, NodePort, ExternalName, and LoadBalancer.
  type: NodePort
  port: 10246
  # nodePort: active only when type is  NodePort
  nodePort: 10246
  # externalName: active only when type is  ExternalName
  externalName: svc-opensergo-control-plane

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
