---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - fault-tolerance.opensergo.io
  resources:
  - CircuitBreakerStrategy
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fault-tolerance.opensergo.io
  resources:
  - CircuitBreakerStrategy/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fault-tolerance.opensergo.io
  resources:
  - ConcurrencyLimitStrategy
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fault-tolerance.opensergo.io
  resources:
  - ConcurrencyLimitStrategy/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fault-tolerance.opensergo.io
  resources:
  - FaultToleranceRule
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fault-tolerance.opensergo.io
  resources:
  - FaultToleranceRule/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fault-tolerance.opensergo.io
  resources:
  - RateLimitStrategy
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fault-tolerance.opensergo.io
  resources:
  - RateLimitStrategy/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fault-tolerance.opensergo.io
  resources:
  - ThrottlingStrategy
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fault-tolerance.opensergo.io
  resources:
  - ThrottlingStrategy/status
  verbs:
  - get
  - patch
  - update
