apiVersion: v1
kind: Service
metadata:
  name: opensergo-control-plane
  namespace: opensergo-system
spec:
  ports:
    - port: 10246
      protocol: TCP
      targetPort: 10246
  selector:
    app: opensergo-control-plane