apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opensergo-control-plane-role
  namespace: opensergo-system
rules:
- apiGroups:
  - fault-tolerance.opensergo.io
  - traffic.opensergo.io
  resources:
  - "*"
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch